### PR TITLE
Check version of MySQL first before rest replication checks

### PR DESCRIPTION
**Pull request by axeoman**
Check the version first and then the rest of the checks, since there is no sense in doing checks on unsupported versions.

### CODE REVIEW

**Review by alexole — APPROVED** [review]
Misclicked.

**Review by alexole — DISMISSED** [review]
I would not like to add the code which has nothing to do with MySQL, as MariaDB is not MySQL, so we don't support that.
Could you try just swapping those lines, so the version check will fail first:
```
self._check_versions_replication_support()            
self._check_gtid_mode_enabled()
```

**Comment by axeoman** [comment]
Agree, updated the commit with only order swap change.

**Review by alexole — APPROVED** [review]
LGTM

**Pull request merged**
